import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  ManyToMany,
  OneToMany,
} from 'typeorm';
import { MusicTag } from './music-tag.entity';

export enum TagClass {
  EMOTION = 'emotion',
  GENRE = 'genre',
  SITUATION = 'situation',
  INSTRUMENT = 'instrument',
  RHYTHM = 'rhythm_beat',
  VOCAL = 'vocal',
  WEATHER = 'weather',
  OTHER = 'other',
}

export enum Tag {
  NAME = 'name',
LOVE = 'love',
ANGRY = 'angry',
SAD = 'sad',
ENJOY = 'enjoy',
TENSION = 'tension',
HAPPY = 'happy',
LONELY = 'lonely',
CONFIDENCE = 'confidence',
COURAGE = 'courage',
BOREDOM = 'boredom',
CONSOLATION = 'consolation',
BALLADE = 'ballade',
ACCOUSTIC = 'accoustic',
METAL = 'metal',
SOUL = 'soul',
HIPHOP = 'hiphop',
ELECTRIC = 'electric',
POP = 'pop',
JAZZ = 'jazz',
CLASSIC = 'classic',
CCM = 'CCM',
TROT = 'trot',
DRIVE = 'drive',
REST = 'rest',
EXERCISE = 'exercise',
WALK = 'walk',
PARTY = 'party',
SORK = 'sork',
STUDY = 'study',
FAREWELL = 'farewell',
DATE = 'date',
RAIN = 'rain',
WIND = 'wind',
SUN = 'sun',
SNOW = 'snow',
THUNDER = 'thunder',
DRY = 'dry',
HOT = 'hot',
HUMID = 'humid',
DRUM = 'drum',
BASS = 'bass',
ELECTRIC_GUITAR = 'electric_guitar',
PIANO_KEYBOARD = 'piano_keyboard',
STRING = 'string',
BRASS = 'brass',
HAND_PERCUSSION = 'hand_percussion',
ACOUSTIC_GUITAR = 'acoustic_guitar',
SWING_BEAT = 'swing_beat',
SHUFFLE_RHYTHM = 'shuffle_rhythm',
DISCO_RHYTHM = 'disco_rhythm',
STRAIGHT_RHYTHM = 'straight_rhythm',
BOUNCE_RHYTHM = 'bounce_rhythm',
HALF_TIME_RHYTHM = 'half_time_rhythm',
TRAP_BEAT = 'trap_beat',
REGGAE_BEAT = 'reggae_beat',
TYPE_BEAT = 'type_beat',
BOOMBAP_BEAT = 'boombap_beat',
MAN = 'man',
WOMAN = 'woman',
MIX = 'mix',
HUSKY = 'husky',
DRAMATIC = 'dramatic',
MIDDLE_TONE = 'middle_tone',
HIGH_TONE = 'high_tone',
CLEAR = 'clear',
NEUTRAL = 'neutral',
DREAMY = 'dreamy',
DISCO = 'disco',
OST = 'ost',
ELECTRONIC_SOUND = 'electronic_sound',
AUTO_TUNE = 'auto_tune',
FALSETTO = 'falsetto',
COUNTRY = 'country',
REGGAE = 'reggae',
POWERFUL = 'powerful',
NECTAROUS = 'nectarous',
FAMILY = 'family',
GROUP = 'group',
BOOMBAP = 'boombap',
TRAP = 'trap',
RATCHET = 'ratchet',
MUMBLE_RAP = 'mumble_rap',
GRIME = 'grime',
GPUNK = 'gpunk',
CLOUD = 'cloud',
REGGAE_TON = 'reggae_ton',
JAZZ_HIPHOP = 'jazz_hiphop',
OLD_SCHOOL = 'old_school',
NEW_SCHOOL = 'new_school',
GANGSTER = 'gangster',
ROCK_ROLL = 'rock_roll',
HEAVY_METAL = 'heavy_metal',
DEATH_METAL = 'death_metal',
ACID_ROCK = 'acid_rock',
ALTERNATIVE_ROCK = 'alternative_rock',
GLAM_ROCK = 'glam_rock',
NEW_WAVE = 'new_wave',
HOUSE = 'house',
TROPICAL_HOUSE = 'tropical_house',
GARAGE = 'garage',
DUBSTEP = 'dubstep',
TRANCE = 'trance',
TECHNO = 'techno',
CHILL_WAVE = 'chill_wave',
DOWN_TEMPO = 'down_tempo',
FUTURE_BASS = 'future_bass',
ELECTRO_POP = 'electro_pop',
EURO_DANCE = 'euro_dance',
HARD_STYLE = 'hard_style',
BIG_ROOM = 'big_room',
ACID_JAZZ = 'acid_jazz',
CONTEMPORARY = 'contemporary',
RAG_TIME = 'rag_time',
HARD_BOP = 'hard_bop',
DIXIELAND = 'dixieland',
COOL_JAZZ = 'cool_jazz',
BIG_BAND = 'big_band',
SWING = 'swing',
BOOGIE_WOOGIE = 'boogie_woogie',
NEW_JACKSWING = 'new_jackswing',
BOSSA_NOVA = 'bossa_nova',
RNB = 'rnb',
PUNK = 'punk',
BLUES = 'blues',
BOOGIE = 'boogie',
EURO_DISCO = 'euro_disco',
NU_DISCO = 'nu_disco',
HIGH_NRG = 'high_nrg',
COSMIC_DISCO = 'cosmic_disco',
NEO_PUNK = 'neo_punk',
DOO_WOP = 'doo_wop',
QUIET_STORM = 'quiet_storm',
NEO_SOUL = 'neo_soul',
SLOW_JAM = 'slow_jam',
ORCHESTRA = 'orchestra',
SKA = 'ska',
ROOTS = 'roots',
DANCE_HALL = 'dance_hall',
HONKY_TONKY = 'honky_tonky',
NASHVILLE_SOUND = 'nashville_sound',
CYMBAL = 'cymbal',
HIHAT = 'hihat',
TOM_TOM = 'tom_tom',
LOWTOM_FLOWTOM = 'lowtom_flowtom',
HIGH_TOM = 'high_tom',
SNARE = 'snare',
BASS_DRUM = 'bass_drum',
EIGHT_ZERO_EIGHT = '808',
ACOUSTIC = 'acoustic',
RIDE_CYMBAL = 'ride_cymbal',
CRASH_CYMBAL = 'crash_cymbal',
CHINA_CYMBAL = 'china_cymbal',
KONTRA_BASS = 'kontra_bass',
FRETLESS_BASS = 'fretless_bass',
HUM_BUCKER = 'hum_bucker',
SYNTH_BASS = 'synth_bass',
ELECTRIC_BASS = 'electric_bass',
PIANO = 'piano',
SYNTH = 'synth',
PIPE_ORGAN = 'pipe_organ',
ACCORDION = 'accordion',
DJEMBE = 'djembe',
CAJON = 'cajon',
SHAKER = 'shaker',
CONGA_BONGO = 'conga_bongo',
TIMBALES = 'timbales',
BUK = 'buk',
TAMBOURINE = 'tambourine',
TRUMPET = 'trumpet',
TROMBONE = 'trombone',
CORNET = 'cornet',
HORN = 'horn',
TUBA = 'tuba',
SAXOPHONE = 'saxophone',
FLUTE = 'flute',
BASSOON = 'bassoon',
OBOE = 'oboe',
CLARINET = 'clarinet',
GUITAR = 'guitar',
UKULELE = 'ukulele',
MANDOLIN = 'mandolin',
BANJO = 'banjo',
VIOLIN = 'violin',
VIOLA = 'viola',
CELLO = 'cello',
DOUBLE_BASS = 'double_bass',
HARP = 'harp',
PERCUSSION = 'percussion',
XYLOPHONE = 'xylophone',
MARIMBA = 'marimba',
VIBRAPHONE = 'vibraphone',
TIMPANI = 'timpani',
WALTZ = 'waltz',
GOGO = 'gogo',
CLASSIC_GUITAR = 'classic_guitar',
MISS = 'miss',
VOCAL_CHORUS = 'vocal_chorus',
}

//TODO: tag, subtag replace string to enum class
@Entity()
export class MusicTagValue {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({ unique: true })
  name: Tag;

  @Column({ nullable: true })
  parent: Tag;

  @Column({
    type: 'enum',
    enum: TagClass,
  })
  class: TagClass;

  @OneToMany(() => MusicTag, (musicTag) => musicTag.music)
  musicTags: MusicTag[];
}
