http:
  port: 3000

database:
  port: 3306
  database: 'favi_test3'
  host: 'localhost'
  type: 'mysql'
  username: 'root'
  password: 'root'
  synchronize: true
  autoLoadEntities: true
  logging: true
  bigNumberStrings: false

auth:
  hashIter: 56178
  jwtSecret: 'arcaneservicemurekabackendbyskeep194'

mail:
  service: 'gmail'
  host: 'smtp.gmail.com'
  port: 587
  secure: false
  auth:
    user: 'official.arcane.inc@gmail.com'
    pass: 'fwdjexwvfhdbdkbd'