http:
  port: 3000

default:
  port: 3306
  database: 'favi_test'
  host: 'localhost'
  type: 'mysql'
  username: 'root'
  password: 'root'
  synchronize: true
  #migrationsRun: true
  autoLoadEntities: true
  logging: true
  bigNumberStrings: false
  entities : ["src/common/entity/**/*.ts"]
auth:
  hashIter: 56718
  jwtSecret: 'arcaneservicemurekabackendbyskeep194'

mail:
  service: 'gmail'
  host: 'smtp.gmail.com'
  port: 587
  secure: false
  auth:
    user: 'official.arcane.inc@gmail.com'
    pass: 'fwdjexwvfhdbdkbd'