http:
  port: 3000

default:
  port: 3306
  database: 'favi'
  host: 'arcanedb.cyu9nbnbjetu.ap-northeast-2.rds.amazonaws.com'
  type: 'mysql'
  username: 'arcane'
  password: 'Arcane123'
  synchronize: false
  autoLoadEntities: true
  logging: true
  bigNumberStrings: false
  # Typeorm: sync 할 땐 아래 줄 주석 취소할 것!
  # entities : ["src/common/entity/**/*.{ts,js}"]

auth:
  hashIter: 56718
  jwtSecret: 'arcaneservicemurekabackendbyskeep194'

mail:
  service: 'gmail'
  host: 'smtp.gmail.com'
  port: 587
  secure: false
  auth:
    user: 'official.arcane.inc@gmail.com'
    pass: 'fwdjexwvfhdbdkbd'